### ISSUE TITLE
Implement Specifications

### ISSUE THREAD

**Issue by andrebaltieri** [andrebaltieri/FluentValidator#19]
Implement a way to use specifications with Validation Contracts and Notifications

**Comment by AlanBessa** [comment]
Quando faço new ValidationContract<T>(this) dentro do construtor de minha Entidade não consigo mais obter a referencia dele do seu pacote. Alguma coisa quebrou, não?

**Comment by andrebaltieri** [comment]
Este pacote foi descontinuado, o novo se chama Flunt!
