### ISSUE TITLE
FluentValidator in .NET Framework

### ISSUE THREAD

**Issue by lira92** [andrebaltieri/FluentValidator#5]
@andrebaltieri FluentValidator will support projects in .NET Framework, including .NET 4.5? Because the package FluentValidator in Nuget doesn't have any updates since 1.0.5 version.

**Comment by andrebaltieri** [comment]
We are moving our support to .NET Standard 1.6 which supports .NET FX 4.6.1.
https://docs.microsoft.com/pt-br/dotnet/standard/net-standard
