### ISSUE TITLE
Criar novo método AddNotifications

### ISSUE THREAD

**Issue by pauloanalista** [andrebaltieri/FluentValidator#6]
Criar um novo método para adicionar notificações das classes notificáveis mais simples.

AddNotifications(cpf, cnpj, dinheiro);

Basta criar um metodo com params

public void AddNotifications(params Notifiable[] objects)
        {
            objects.ToList().ForEach(x => _notifications.AddRange(x.Notifications));
        }

**Comment by andrebaltieri** [comment]
Hi Paulo, can you provide a case you need this?

**Comment by angelobelchior** [comment]
I think the best way to do that is to create an Extension Method to Validate Contract class:
```csharp
namespace FluentValidator.Validation
{
    public static class MyValidators
    {
        public static ValidationContract IsCPF(ValidationContract self,
                                               string value,
                                               string property,
                                               string message)
        {
            /*Magic*/
            return self;
        }
    }
}
```

**Comment by yanjustino** [comment]
I proposed in PR #13 to improve this.
