### ISSUE TITLE
Dar suporte a globalização

### ISSUE THREAD

**Issue by pauloanalista** [andrebaltieri/FluentValidator#7]
Idioma padrão está em inglês, mas como estamos no Brasil o usuário vê somente mensagens em português.

Jogar em um Resource já resolve. :)

**Comment by lira92** [comment]
@pauloanalista tem como customizar a mensagem.

**Comment by pauloanalista** [comment]
Mas se vc esta usando do Brasil vc é obrigado a customizar todas as mensagens. No meu prmToolkit.NotificationPatner que é parecido, eu tenho mensagem padrão em 2 idiomas.

Se a cultura é pt-Br ja vem em português. Uso sem passar mensagens

**Comment by andrebaltieri** [comment]
This is not intend to be a Brazilian package only. As english is the most used language, we support this as default. You can customize your messages if you want.
