### ISSUE TITLE
Criar método isRequiredWithLenth ou algo do tipo

### ISSUE THREAD

**Issue by pauloanalista** [andrebaltieri/FluentValidator#8]
A ideia é dizer que o objeto é obrigatório com tamanho mínimo e máximo.

isRequiredWithLenth(x=> x.Propriedade, 3, 20, "O campo Propriedade deve ter entre 3 a 20 caracteres);

**Comment by lira92** [comment]
@pauloanalista seria um atalho pro IsGreaterThan e IsLowerThan usados juntos?

**Comment by pauloanalista** [comment]
Exatamente

**Comment by andrebaltieri** [comment]
Hey guys, you can compose the contract...
```
contract.IsRequired(x=>x.String).HasMaxLen(...).HasMinLen();
```

Is that what are you looking for?
